### PR TITLE
AgoricMining_Glibx Pledge

### PR DESCRIPTION
**Pull request by glibxinc**
moniker: AgoricMining_Glibx
email1: [info@glibx.com](mailto:info@glibx.com)
email2: [agoricmining@gmail.com](mailto:agoricmining@gmail.com)

### CODE REVIEW

**Review by jeetraut — CHANGES_REQUESTED** [review]
Add explorer link

**Review by emmanuelapp — APPROVED** [review]
👍🏾

**Comment by dckc** [comment]
related work noted in discord March 17: https://docs.agoricmining.com/guides/agoric-validator-guide

**Comment by jeetraut** [comment]
Twitter space speaking: https://twitter.com/i/spaces/1lDxLLkozwPxm

**Pull request merged**
